version = "Two"
use_small_heuristics = "Max"
merge_derives = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Use field initialize shorthand if possible
use_field_init_shorthand = true

reorder_imports = true